require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.1
  TargetRailsVersion: 7.0.8
  NewCops: enable

  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes