
default: &default
  adapter: postgresql
  encoding: unicode
  username: aba_network
  password: 1345
  port: 5433
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aba_network_development

test:
  <<: *default
  database: aba_network_test

production:
  <<: *default
  database: aba_network_production
  username: aba_network
  password: <%= ENV["ABA_NETWORK_DATABASE_PASSWORD"] %>
  